version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: >-
    nuget restore Akismet.Net.sln
build:
  verbosity: minimal
artifacts:
- path: Akismet.Net\bin\Release\AkismetApi.Net.*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: 1ccOBZHCoPjWklcbi1Lf6ED+4muXi3r21eswoSuzbi7C1QDhcQC+MkXA5fBd4XNL
  artifact: /AkismetApi.Net\.(.*)\.nupkg/
