version: 2.0.0.{build}
image: Visual Studio 2022
configuration: Release
before_build:
- ps: >-
    dotnet restore
build:
  verbosity: minimal
artifacts:
- path: Akismet.Net\bin\Release\AkismetApi.Net.*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: nqEtiFeObp2SebFXE3i0DHiBPkg3qVON4UadOTsfhpof/W6xZgEMGFDBG/brjwO0
  artifact: /AkismetApi.Net\.(.*)\.nupkg/
