version: 3.0.0.{build}
image: Visual Studio 2022
configuration: Release
environment:
  AKISMET_API_KEY:
    secure: 6UGrjZWtUhsSK42Esp2yNA==
  AKISMET_API_KEY_URL: https://www.adamh.us
before_build:
- ps: >-
    echo $env:AKISMET_API_KEY_URL
    dotnet restore
build:
  verbosity: minimal
artifacts:
- path: Akismet.Net\bin\Release\AkismetApi.Net.*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: 1ccOBZHCoPjWklcbi1Lf6ED+4muXi3r21eswoSuzbi7C1QDhcQC+MkXA5fBd4XNL
  artifact: /AkismetApi.Net\.(.*)\.nupkg/
